# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$ ->
  $form = $('#payment-form')
  $form.submit (event) ->
    # Disable the submit button to prevent repeated clicks:
    $form.find('.submit').prop 'disabled', true
    # Request a token from Stripe:
    Stripe.card.createToken $form, stripeResponseHandler
    # Prevent the form from being submitted:
    false
  return

# ---
# generated by js2coffee 2.2.0